### ISSUE TITLE
Cannot login to YIM from pidgin

### ISSUE THREAD

**Issue by alexolog** [EionRobb/funyahoo-plusplus#60] opened 2018-01-13 16:08 UTC
Using the official web interface works fine.

Log: https://paste.ee/p/XiTd7

**Comment by dequis** [comment] 2018-01-13 16:31
Is this your first time using the plugin in 6+ months?

**Comment by alexolog** [comment] 2018-01-13 17:57
I haven't been using it for a while.

**Comment by dequis** [comment] 2018-01-13 19:44
Then that's a duplicate of #51

**Closed by dequis** 2018-01-13 19:44 UTC
