### ISSUE TITLE
Updated DLL?

### ISSUE THREAD

**Issue by ToeJet** [EionRobb/funyahoo-plusplus#58] opened 2017-11-16 20:50 UTC
The readme on the main page indicates to download the precompiled windows DLL from http://dequis.org/libyahoo-plusplus.dll.  Looks like the project has updated since the DLL was built.  Is there a new build?   Currently the account will connect then immediately disconnect from yahoo.   Would like to try the latest code to determine if it is an issue.

**Comment by dequis** [comment] 2017-11-18 19:06
No, that commit doesn't fix it

Duplicate of #51

**Closed by dequis** 2017-11-18 19:06 UTC
