### ISSUE TITLE
Crashes after adding account

### ISSUE THREAD

**Issue by RevStrangeHope** [EionRobb/funyahoo-plusplus#61] opened 2018-02-12 19:22 UTC
Pidgin Fully crashes after adding account unsure what is causing this. hope this information proves useful.

```
System Info
OS: Ubuntu 16.04.3 LTS x86_64
Kernel: 4.4.0-112-generic
DE: Xfce
WM: Xfwm4
```

**Comment by dequis** [comment] 2018-02-12 20:54
Duplicate of #61

**Closed by dequis** 2018-02-12 20:55 UTC

**Comment by RevStrangeHope** [comment] 2018-02-12 21:11
what are you on about? this isn't a Duplicate

**Comment by dequis** [comment] 2018-02-12 21:50
Oh sorry I wrote the wrong ticket number. #57
