### ISSUE TITLE
Messages send, but responses never arrive

### ISSUE THREAD

**Issue by Bearded-Blunder** [EionRobb/funyahoo-plusplus#34] opened 2016-09-12 23:28 UTC
Messages send and show up at the other end, but responses from my contacts never arrive, only showing up if I subsequently login using the official client and only showing up there. This is running under Windows 10, I've not tried on Linux, and is in addition to problems corresponding to issues #2 (not such a big deal) and #30 (bigger deal resulting in long startup times and/or complete hangs) in the case of #30 this only happens for some contacts, and not others.

I'm hoping you make a breakthrough, as pidgin allows setting fonts and font sizes which the new official client lacks the ability to do, a feature my 73yo mother needs in order to use YIM as she finds their new interface too difficult to read.  I could shift her onto a different network easily enough, but shifting her contacts to it as well is problematic.

**Comment by EionRobb** [comment] 2016-09-12 23:29
Please get a debug log (from the buddy list, Help->Debug Window) while someone sends you a message that you're not seeing.

**Comment by dequis** [comment] 2016-09-13 00:41
While what eion requested still stands, because we need it to fix things, maaaaybe...

>as pidgin allows setting fonts and font sizes

...you could install a browser extension such as stylish ([chrome](https://chrome.google.com/webstore/detail/stylish/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en), [firefox](https://addons.mozilla.org/en-US/firefox/addon/stylish/)), from the stylish menu pick "write a style for messenger.yahoo.com", and copypaste this code:

```
* {
    font-family: "Arial" !important;
    font-weight: bold !important;
    font-size: 18px !important;
}
```

Not sure if that's enough, tweak as you wish. Maybe add `color: black !important;` to make all the fonts black.

You can also press control + (plus key) to increase the size of everything proportionally, in which case it might help to make the sidebar somewhat smaller with:

```
.content > .col1 {
    width: 250px !important;
}
.content > .col2 {
    left: 250px !important;
}

.list-item-timestamp {
    display: none;
}
```

**Comment by Bearded-Blunder** [comment] 2016-09-13 01:17
@EionRobb  Will try, just tried to reproduce it from my mother's account and laptop downstairs, but that's working, some reason it hasn't been from across the road at my sister's, can't do much to test that right now, don't think invading her house at 2:15am to send myself a message would be very popular!  Phoning her to message me even less so.

**Comment by EionRobb** [comment] 2016-09-13 01:30
@Bearded-Blunder that's a risk I'm willing to take! ;) 

Sure, just whenever.

**Comment by Bearded-Blunder** [comment] 2016-09-13 20:09
Since using the official client to clear conversations for the two contacts which were loading up old messages on start, I am no longer able to reproduce this (the problem went away).  Even though it was a third contact who was unable to send to me.  Should I close this?

**Comment by dequis** [comment] 2016-09-13 21:25
BTW i've found that using the clear conversations feature of the official client breaks things, [see this comment for details](https://github.com/EionRobb/funyahoo-plusplus/issues/23#issuecomment-246214865). Does that description match your experience, or is everything working fine?

**Comment by Bearded-Blunder** [comment] 2016-09-13 21:59
Um, it cured all the beeping and a (literal) half hour delay signing in, so far everything I've done appears to work, however, I haven't tried talking with those particular contacts, they're not online often, and tend to message me if/when they want to talk, so I can't comment on if it has broken talking to them until they try, if it fails they have other means to contact me, and I'll find out that way.

**Comment by dequis** [comment] 2016-09-13 23:55
>a (literal) half hour delay signing in

Jesus christ what.

**Comment by Bearded-Blunder** [comment] 2016-09-14 00:26
That's how long it was taking to load up (and log yet again) all that was said going right back to January, I'd seen warnings of potential issues clearing the logs here and on yahoo's forum, but I had to do something, "loading old messages" wasn't a minor inconvenience, was a major headache. during which time I could do nothing in pidgin, as it constantly flipped focus between windows and added and removed (not responding) to the title bar..  fortunately getting rid of that chat history seemed to cure it.

**Comment by geniuswithaces** [comment] 2016-09-14 03:01
i have seen very long logins as well.. i dont think it was that long, but part of it was the old messages being downloaded, but as was mentioned earlier. clearing them from the server screws others things up.   I have noticed using the timestamp plugins gave me errors, so i unchecked them and would say if something looks strange... disable the extra plugins. it only adds additional layers and possible problems.

**Comment by dequis** [comment] 2016-09-16 04:28
Well, closing this one since the main issue can't be reproduced anymore.

For the secondary issue (too many old messages), that'd be a dupe of #30 (which i think is mostly fixed already but i could be wrong)

**Closed by dequis** 2016-09-16 04:28 UTC
