### ISSUE TITLE
When used with Spectrum 2, sometimes real names are not sent to Spectrum 2.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [EionRobb/funyahoo-plusplus#42] opened 2017-02-05 07:13 UTC
When used with Spectrum 2, funyahoo-plusplus sometimes real names are not sent to Spectrum 2. This is similar to a problem with Facebook's plugin where only about 30% of all contacts have Real names. When a new friend is addeed, their friend request does show Real name in ( ) but in the list they look like an extremely long UIN only..

**Comment by EionRobb** [comment] 2017-02-05 08:49
Bitlbee had a similar issue where there was a bit of a 'thread race' (although, without threads) where it would show uid's instead of aliases for some buddies depending on when the alias was updated (eg, if the buddy with its alias was added to the buddy list, or if the alias came later) - could there be something similar happening with spectrum2?

**Comment by Zombie-Ryushu** [comment] 2017-02-05 08:52
I can't tell. I've got a similar issue with purple-facebook. Under bitlbee, purple-facebook displays nothing but UIN.

**Comment by dequis** [comment] 2017-02-05 14:57
Referencing https://github.com/hanzz/spectrum2/issues/181 https://github.com/dequis/purple-facebook/issues/295

>Under bitlbee, purple-facebook displays nothing but UIN.

That particular case is intended behavior, which is why I told you to use bitlbee-facebook instead. Not actually related to this issue.

More specifically: bitlbee defaults to username for nicks for purple things almost always. Users were expected to set nick_format to %full_name in the protocols that have non-human-readable usernames. In the last release I added a small [whitelist][1] of protocols to set that value automatically. That list deliberately excludes purple-facebook.

All of that is irrelevant for spectrum. It just sends both username and full name because xmpp has fields for both things.

[1]: https://github.com/bitlbee/bitlbee/blob/3.5.1/protocols/purple/purple.c#L118-L128

>Bitlbee had a similar issue where there was a bit of a 'thread race' (although, without threads) where it would show uid's instead of aliases for some buddies depending on when the alias was updated (eg, if the buddy with its alias was added to the buddy list, or if the alias came later) - could there be something similar happening with spectrum2?

That's an interesting point but I don't think so. That one happened with skypeweb only (and unusual nick_format values). Don't know about funyahoo (bloody mess, I don't think we ever figured out what the intended order of things is supposed to be) but i'm sure facebook waits for the contact list to be completely fetched before starting the mqtt connection where presences are received.

**Comment by Zombie-Ryushu** [comment] 2017-02-05 17:15
With the whitelist thing, you might want to alter that to be a config option. There are other purple modules out there.

**Comment by dequis** [comment] 2017-02-05 21:15
The config option has always existed, it's called nick_format and users can still do that for other plugins if they want. The whitelist is only for convenience with popular plugins (that is, all the ones i know).

**Comment by Zombie-Ryushu** [comment] 2017-02-05 21:20
I didn't know that, but I can verify that the User info page is blank even when using regular Pidgin.

**Comment by dequis** [comment] 2017-04-02 07:58
Closing since it's an ejabberd/spectrum issue

Quoting myself from https://github.com/dequis/purple-facebook/issues/295#issuecomment-290971148

>I installed spectrum and ejabberd and tested this myself, no issues.
>
>The other ticket mentions some stuff about remote roster. That appears to be something added to ejabberd 14.05. You're using "2.1.13". There's your problem.

**Closed by dequis** 2017-04-02 07:58 UTC
